1. Write a R program to convert a given matrix to a 1 dimensional array.

In [5]:
#1
mat_ar <- matrix(c(1:12), 3, 4)
as_vec <- c(mat_ar)
print(mat_ar)
print(as_vec)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12
 [1]  1  2  3  4  5  6  7  8  9 10 11 12


In [ ]:
# Create a matrix 'm' with 3 rows and 4 columns filled with values from 1 to 12
m = matrix(1:12, 3, 4)

# Print a message indicating the original matrix
print("Original matrix:")

# Display the original matrix
print(m)

# Convert the matrix 'm' to a 1-dimensional array
a = as.vector(m)

# Print a message indicating the 1-dimensional array
print("1 dimensional array:")

# Display the 1-dimensional array
print(a)


2. Write a R program to create an array of two 3x3 matrices each with 3 rows and 3 columns from two given two vectors.

In [ ]:
#2
vec1 <- c(1:20)
vec2 <- c(50:70)
mat_2 <- array(c(vec1, vec2), dim = c(3, 3, 2))
print(mat_2)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18



3. Write a R program to create an 3 dimensional array of 24 elements using the dim() function.

In [12]:
mat_3 <- array(c(1:24), dim=c(3,3))
print(mat_3)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [13]:
# Generate a vector 'v' with 24 random integers between 1 and 5, allowing replacement
v = sample(1:5, 24, replace = TRUE)

# Reshape the vector 'v' into a 3-dimensional array with dimensions 3x2x4
dim(v) = c(3, 2, 4)

# Print a message indicating the output is a 3-dimensional array
print("3-dimension array:")

# Display the contents of the 3-dimensional array
print(v)


[1] "3-dimension array:"
, , 1

     [,1] [,2]
[1,]    2    2
[2,]    5    4
[3,]    4    3

, , 2

     [,1] [,2]
[1,]    2    3
[2,]    2    2
[3,]    1    4

, , 3

     [,1] [,2]
[1,]    2    3
[2,]    1    5
[3,]    2    4

, , 4

     [,1] [,2]
[1,]    3    2
[2,]    5    1
[3,]    4    5



4. Write a R program to create an array of two 3x3 matrices each with 3 rows and 3 columns from two given two vectors. Print the second row of the second matrix of the array and the element in the 3rd row and 3rd column of the 1st matrix.

In [19]:
vec41 <- c(1:5)
vec42 <- c(50:60)
mat_4 <- array(c(vec41, vec42), dim = c(3, 3, 2))
print(mat_4)
print(mat_4[2, , 2])
print(mat_4[3, 3, 1])

, , 1

     [,1] [,2] [,3]
[1,]    1    4   51
[2,]    2    5   52
[3,]    3   50   53

, , 2

     [,1] [,2] [,3]
[1,]   54   57   60
[2,]   55   58    1
[3,]   56   59    2

[1] 55 58  1
[1] 53


5. Write a R program to combine three arrays so that the first row of the first array is followed by the first row of the second array and then first row of the third array.

In [30]:
mat5_1 <- matrix(c(1:9), 3, 3)
mat5_2 <- matrix(c(10:18), 3, 3)
mat5_3 <- matrix(c(20:28), 3, 3)
mat_5 <- t(rbind(mat5_1, mat5_2, mat5_3))
b <- matrix(t(cbind(mat5_1, mat5_2, mat5_3)), ncol = 3, byrow = T)
print(b)
print(mat_5)

      [,1] [,2] [,3]
 [1,]    1    4    7
 [2,]   10   13   16
 [3,]   20   23   26
 [4,]    2    5    8
 [5,]   11   14   17
 [6,]   21   24   27
 [7,]    3    6    9
 [8,]   12   15   18
 [9,]   22   25   28
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
[1,]    1    2    3   10   11   12   20   21   22
[2,]    4    5    6   13   14   15   23   24   25
[3,]    7    8    9   16   17   18   26   27   28


In [ ]:
# Link to reference or additional information
# https://bit.ly/2QkvW10

# Create the first array 'num1' with rows "A", "B", and "C", each repeated 3 times
num1 = rbind(rep("A",3), rep("B",3), rep("C",3))

# Print a label for 'num1'
print("num1")

# Print the content of 'num1'
print(num1)

# Create the second array 'num2' with rows "P", "Q", and "R", each repeated 3 times
num2 = rbind(rep("P",3), rep("Q",3), rep("R",3))

# Print a label for 'num2'
print("num2")

# Print the content of 'num2'
print(num2)

# Create the third array 'num3' with rows "X", "Y", and "Z", each repeated 3 times
num3 = rbind(rep("X",3), rep("Y",3), rep("Z",3))

# Print a label for 'num3'
print("num3")

# Print the content of 'num3'
print(num3)

# Combine the three arrays by first combining them column-wise, then transposing, and converting to a matrix with 3 columns
a = matrix(t(cbind(num1,num2,num3)), ncol=3, byrow=T)

# Print a label for the combined array
print("Combine three arrays, taking one row from each one by one:")

# Print the combined array
print(a)


6. Write a R program to create an array using four given columns, three given rows, and two given tables and display the content of the array.

In [31]:
# Create a 3-dimensional array with values from 1 to 30
# The array has dimensions 3 rows, 4 columns, and 2 matrices (tables)
array6 <- array(1:30, dim = c(3, 4, 2))

# Print the content of the 3-dimensional array to the console
print(array6)


, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24



7. Write a R program to create a two-dimensional 5x3 array of sequence of even integers greater than 50.

In [36]:
array7 <- array(seq(from = 50, length.out = 30, by = 2), dim = c(5, 3, 2))
print(array7)

, , 1

     [,1] [,2] [,3]
[1,]   50   60   70
[2,]   52   62   72
[3,]   54   64   74
[4,]   56   66   76
[5,]   58   68   78

, , 2

     [,1] [,2] [,3]
[1,]   80   90  100
[2,]   82   92  102
[3,]   84   94  104
[4,]   86   96  106
[5,]   88   98  108

