1. Write a R program to create a list containing strings, numbers, vectors and a logical values.






15. Write a R program to create a list named s containing sequence of 15 capital letters, starting from ‘E’.

16. Write a R program to Add 10 to each element of the first vector in a given list.

17. Write a R program to extract all elements except the third element of the first vector of a given list.
18. Write a R program to add a new item g4 = "Python" to a given list.

19. Write a R program to assign new names "a", "b" and "c" to the elements of a given list.
20. Write a R program to get the length of the first two vectors of a given list.

21. Write a R program to find all elements of a given list that are not in another given list.

In [4]:
l <- list(
    c('a', 'b', 'c'),
    5,
    c(1, 2, 2, 5, 7, 12),  # Numeric vector
    matrix(c(3, -8, 1, -3), nrow = 2),  # 2x2 matrix
    TRUE
)
print(l)

[[1]]
[1] "a" "b" "c"

[[2]]
[1] 5

[[3]]
[1]  1  2  2  5  7 12

[[4]]
     [,1] [,2]
[1,]    3    1
[2,]   -8   -3

[[5]]
[1] TRUE



2. Write a R program to list containing a vector, a matrix and a list and give names to the elements in the list.

In [8]:
# Create a list containing a vector, a matrix, and another list
list_data <- list(c("Red", "Green", "Black"),     # Vector of color names
                  matrix(c(1,3,5,7,9,11), nrow = 2),  # 2x3 matrix of odd numbers
                  list("Python", "PHP", "Java"))      # List of programming languages

# Print the original list
print("List:")
print(list_data)

# Assign names to the elements in the list
names(list_data) <- c("Color", "Odd numbers", "Language(s)")

# Print the list with the assigned column names
print("List with column names:")
print(list_data)


[1] "List:"
[[1]]
[1] "Red"   "Green" "Black"

[[2]]
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    3    7   11

[[3]]
[[3]][[1]]
[1] "Python"

[[3]][[2]]
[1] "PHP"

[[3]][[3]]
[1] "Java"




[1] "List with column names:"
$Color
[1] "Red"   "Green" "Black"

$`Odd numbers`
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    3    7   11

$`Language(s)`
$`Language(s)`[[1]]
[1] "Python"

$`Language(s)`[[2]]
[1] "PHP"

$`Language(s)`[[3]]
[1] "Java"




3. Write a R program to create a list containing a vector, a matrix and a list and give names to the elements in the list. Access the first and second element of the list.

In [6]:
print(list_data["Color"])
print(list_data[2])

$Color
[1] "Red"   "Green" "Black"



$`Odd numbers`
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    3    7   11



4. Write a R program to create a list containing a vector, a matrix and a list and add element at the end of the list.

In [7]:
#append(list_data, "c(5, 6)")
list_data[4] <- 10.5
print(list_data[4])
print(list_data)

[[1]]
[1] 10.5

$Color
[1] "Red"   "Green" "Black"

$`Odd numbers`
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    3    7   11

$`Language(s)`
$`Language(s)`[[1]]
[1] "Python"

$`Language(s)`[[2]]
[1] "PHP"

$`Language(s)`[[3]]
[1] "Java"


[[4]]
[1] 10.5



5. Write a R program to select second element of a given nested list.

In [8]:
print(list_data[2])

$`Odd numbers`
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    3    7   11



6. Write a R program to create a list containing a vector, a matrix and a list and remove the second element.

In [9]:
newlist <- list_data[-2]
newlist

$Color
[1] "Red"   "Green" "Black"

$`Language(s)`
$`Language(s)`[[1]]
[1] "Python"

$`Language(s)`[[2]]
[1] "PHP"

$`Language(s)`[[3]]
[1] "Java"


[[3]]
[1] 10.5

7. Write a R program to create a list containing a vector, a matrix and a list and update the last element.

In [12]:
newlist_2 <- list_data
# append(newlist_2, 'R')



$Color
[1] "Red"   "Green" "Black"

$`Odd numbers`
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    3    7   11

$`Language(s)`
$`Language(s)`[[1]]
[1] "Python"

$`Language(s)`[[2]]
[1] "PHP"

$`Language(s)`[[3]]
[1] "Java"


[[4]]
[1] 10.5

[[5]]
[1] "R"

In [7]:
# Create a list containing a vector, a matrix, and another list
list_data <- list(c("Red", "Green", "Black"), matrix(c(1, 3, 5, 7, 9, 11), nrow = 2),
list("Python"))

# Print the current state of the list
print("List:")
print(list_data)

# Print a message indicating the next operation
print("Update the third element of the list:")

# Update the third element of the list with a new value
list_data[3] = "R programming"

# Print the updated state of the list
print("New list:")
print(list_data)

[1] "List:"
[[1]]
[1] "Red"   "Green" "Black"

[[2]]
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    3    7   11

[[3]]
[[3]][[1]]
[1] "Python"


[1] "Update the third element of the list:"
[1] "New list:"
[[1]]
[1] "Red"   "Green" "Black"

[[2]]
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    3    7   11

[[3]]
[1] "R programming"



8. Write a R program to merge two given lists into one list.

In [6]:
a <- list(c(1, 2, 3), c(2, 34, 2))
b <- list(c(1, 2), c(2, 3, 2, 1))
c <- list(c("sdf", 3, 2))
joint_list <- c(a, b, c)
joint_list

[[1]]
[1] 1 2 3

[[2]]
[1]  2 34  2

[[3]]
[1] 1 2

[[4]]
[1] 2 3 2 1

[[5]]
[1] "sdf" "3"   "2"

9. Write a R program to convert a given list to vector.

In [11]:
my_list <- list(A = c(1, 2, 3),
                B = c(4, 5),
                C = 6)
new_vector <- unlist(my_list, use.names = FALSE)
new_vector

[1] 1 2 3 4 5 6

In [ ]:
# Create the first list containing numbers
n1 = list(1,2,3)

# Create the second list containing numbers
c1 = list(4,5,6)

# Print the message indicating the start of the original lists
print("Original lists:")

# Print the first list
print(n1)

# Print the second list
print(c1)

# Print the message indicating the start of conversion to vectors
print("Convert the lists to vectors:")

# Convert the first list to a vector
v1 = unlist(n1)

# Convert the second list to a vector
v2 = unlist(c1)

# Print the vector created from the first list
print(v1)

# Print the vector created from the second list
print(v2)

# Print the message indicating the start of adding two vectors
print("Add two vectors:")

# Add the two vectors element-wise
v = v1 + v2

# Print the resulting vector after addition
print("New vector:")

# Print the new vector
print(v)


10. Write a R program to create a list of dataframes and access each of those dataframes from the list.

In [12]:
 # Create the first dataframe with columns y1 and y2
df1 = data.frame(y1 = c(0, 1, 2), y2 = c(3, 4, 5))

# Create the second dataframe with columns y1 and y2
df2 = data.frame(y1 = c(6, 7, 8), y2 = c(9, 10, 11))

# Combine the two dataframes into a list
new_list = list(df1, df2)

# Print a message indicating the new list
print("New list:")

# Print the new list containing the dataframes
print(new_list)

# Print a message indicating the first dataframe
print("Data frame-1")

# Print the first dataframe from the list
print(new_list[[1]])

# Print a message indicating the second dataframe
print("Data frame-2")

# Print the second dataframe from the list
print(new_list[[2]])


[1] "New list:"
[[1]]
  y1 y2
1  0  3
2  1  4
3  2  5

[[2]]
  y1 y2
1  6  9
2  7 10
3  8 11

[1] "Data frame-1"
  y1 y2
1  0  3
2  1  4
3  2  5
[1] "Data frame-2"
  y1 y2
1  6  9
2  7 10
3  8 11


11. Write a R program to count number of objects in a given list.

In [13]:
list_data_11 <- list(c("Red", "Green", "Black"), matrix(c(1, 3, 5, 7, 9, 11), nrow = 2), list("Python"))
print(length(list_data_11))

[1] 3


12. Write a R program to convert a given dataframe to a list by rows.

In [14]:
df_12 <- data.frame(y1 = c(0, 1, 2), y2 = c(3, 4, 5))
new_list_12 <- split(df_12, seq(nrow(df_12)))
print(new_list_12)

$`1`
  y1 y2
1  0  3

$`2`
  y1 y2
2  1  4

$`3`
  y1 y2
3  2  5



In [15]:
# Create a data frame with student exam data
exam_data = data.frame(
  name = c('Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'),
  score = c(12.5, 9, 16.5, 12, 9, 20, 14.5, 13.5, 8, 19),
  attempts = c(1, 3, 2, 3, 2, 3, 1, 1, 2, 1),
  qualify = c('yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes')
)

# Print the original data frame
print("Original dataframe:")
print(exam_data)

# Convert each row of the data frame to a separate list element
new_list = split(exam_data, seq(nrow(exam_data)))

# Print the list created from the data frame rows
print("dataframe rows to a list:")
print(new_list)


[1] "Original dataframe:"
        name score attempts qualify
1  Anastasia  12.5        1     yes
2       Dima   9.0        3      no
3  Katherine  16.5        2     yes
4      James  12.0        3      no
5      Emily   9.0        2      no
6    Michael  20.0        3     yes
7    Matthew  14.5        1     yes
8      Laura  13.5        1      no
9      Kevin   8.0        2      no
10     Jonas  19.0        1     yes
[1] "dataframe rows to a list:"
$`1`
       name score attempts qualify
1 Anastasia  12.5        1     yes

$`2`
  name score attempts qualify
2 Dima     9        3      no

$`3`
       name score attempts qualify
3 Katherine  16.5        2     yes

$`4`
   name score attempts qualify
4 James    12        3      no

$`5`
   name score attempts qualify
5 Emily     9        2      no

$`6`
     name score attempts qualify
6 Michael    20        3     yes

$`7`
     name score attempts qualify
7 Matthew  14.5        1     yes

$`8`
   name score attempts qualify
8 Laura  13.

13. Write a R program to convert a given matrix to a list.

In [17]:
m_13 <- matrix(c(1, 3, 5, 7, 9, 11), nrow = 2)
l_13 <- split(m_13, rep(1: ncol(m_13), each = nrow(m_13)))
l_13

$`1`
[1] 1 3

$`2`
[1] 5 7

$`3`
[1]  9 11

In [18]:
ma <- cbind(x = 1:10, y = (-4:5)^2)
 split(ma, col(ma))
 
 split(1:10, 1:2)

$`1`
 [1]  1  2  3  4  5  6  7  8  9 10

$`2`
 [1] 16  9  4  1  0  1  4  9 16 25

$`1`
[1] 1 3 5 7 9

$`2`
[1]  2  4  6  8 10

In [ ]:
# Create a matrix with values from 1 to 10, having 2 rows and 2 columns
m = matrix(1:10, nrow = 2, ncol = 2)

# Print the message indicating the original matrix
print("Original matrix:")

# Print the original matrix
print(m)

# Convert the matrix into a list by splitting it column-wise
l = split(m, rep(1:ncol(m), each = nrow(m)))

# Print the message indicating the list derived from the matrix
print("list from the said matrix:")

# Print the resulting list
print(l)


14. Write a R program to assign NULL to a given list element.